---
services:
  traefik:
    image: "docker.io/traefik:v2.10"
    container_name: "traefik"
    volumes:
      - "${DOCKER_HOST:-/var/run/docker.sock}:/var/run/docker.sock:ro"
      - "./etc:/etc/traefik"
    networks:
      - "traefik-global-proxy"
    ports:
      - "80:80"
    labels:
      # enable the dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  traefik-global-proxy:
    name: "traefik-global-proxy"
    external: true
